hours:
  key_name: 'Testing'
  deployment:
    repository:
    deploy_to:
    branch: master
    stages:
      - staging
    staging:
      user:
      branch: master
      hosts:
        web: example.example.com
        app: example.example.com
        db:  example.example.com
      god:
        app_path:   config/god.conf
        sites_path: /usr/local/god/site-conf
      default_environment:
        PATH: rbenv_path_information:$PATH
        PKG_CONFIG_PATH: /usr/local/lib/pkgconfig:/usr/lib/pkgconfig
push:
  server: http://faye/server:9020
  token: putatokenherethatissecureandhiddenfromusers
rubycas:
  cas_base_url: https://link.to.cas/cas
  validate_url: https://link.to.saml/samlValidate
  cas_destination_logout_param_name: url
  baseurl:
    keycards:
      enabled: true
